# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleDriveTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GoogleDriveTest
  pod 'GoogleAPIClientForREST/Drive', '~> 1.1.1'
  pod 'GTMOAuth2', '~> 1.1.4'
  target 'GoogleDriveTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
